In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score,roc_auc_score,f1_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression,PassiveAggressiveClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
sns.set(style='darkgrid')

In [2]:
data = pd.read_csv('../data/clean_data.csv')
data.head()

,y_hat,Category_Car Electronics,Category_Performance & Non-auto,Category_Tires & Wheels,Region_Midwest,Region_Northeast,Region_Northwest,Region_Pacific,Region_Southeast,Region_Southwest,...,Opportunity Amount > 300000,Opportunity Amount > 250000,Opportunity Amount > 200000,Opportunity Amount > 150000,Opportunity Amount > 100000,Opportunity Amount > 50000,Opportunity Amount > 25000,Opportunity Amount > 10000,Opportunity Amount > 5000,Opportunity Amount > 1000
0,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,1
3,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,1,1,1

In [4]:
X = data.drop(columns='y_hat')

In [5]:
y = data['y_hat']

In [6]:
X1 = poly.fit_transform(X)

In [7]:
df = pd.DataFrame(X1, columns=poly.get_feature_names(list(X.columns)))

In [8]:
df['y_hat'] = y

In [9]:
X = df.drop(columns='y_hat')

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

## Modeling

In [13]:
logreg_class = LogisticRegression()
logreg_class.fit(X_train, y_train)

C:\Users\oaher\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [17]:
def accuracy_score_eval(model,train, test):
    return accuracy_score(test,model.predict(train))

In [18]:
def roc_auc_score_eval(model,train, test):
    return roc_auc_score(test,model.predict(train))

In [15]:
def f1_eval(model,train, test):
    return f1_score(test,model.predict(train))

In [16]:

print(f'logreg_class-train = {f1_eval(logreg_class, X_train, y_train)}', f'logreg_class-test = {f1_eval(logreg_class, X_test, y_test)}')

logreg_class-train = 0.5133060388945753 logreg_class-test = 0.4503770739064856

In [19]:
print(f'logreg_class-train = {accuracy_score_eval(logreg_class, X_train, y_train)}', f'logreg_class-test = {accuracy_score_eval(logreg_class, X_test, y_test)}')

logreg_class-train = 0.8373719582057904 logreg_class-test = 0.8130610988559996

In [20]:
print(f'logreg_class-train = {roc_auc_score_eval(logreg_class, X_train, y_train)}', f'logreg_class-test = {roc_auc_score_eval(logreg_class, X_test, y_test)}')

logreg_class-train = 0.6755092470505661 logreg_class-test = 0.6449302646616505

In [21]:
logreg_class.coef_

array([[-0.02753904, -0.15169173, -0.15568595, ...,  0.00092616,
         0.00092616,  0.23447091]])

In [23]:
coeficient = {X.columns[i]:[logreg_class.coef_[0][i]] for i in range(len(X.columns))}

In [24]:
coeficient = pd.DataFrame(coeficient, index=['Coeficient']).T.sort_values('Coeficient')

In [26]:
coeficient = coeficient.sort_values(['Coeficient'],ascending=False)

In [28]:
coeficient.head(50)

                                                    Coeficient
Competitor_None Client Size By Employee Count_3...    1.485763
Region_Southeast Competitor_Unknown Revenue Fro...    1.370363
Region_Northwest Revenue From Client Past Two Y...    1.364733
Region_Northwest Client Size By Revenue_3 Clien...    1.279442
Region_Pacific Client Size By Revenue_3 Opportu...    1.213043
Region_Southeast Client Size By Revenue_2 Clien...    1.174065
Region_Midwest POS_Reseller Opportunity Amount ...    1.171777
POS_Reseller Competitor_None Client Size By Emp...    1.170683
Category_Performance & Non-auto Client Size By ...    1.167787
Competitor_Unknown Client Size By Employee Coun...    1.159493
Region_Pacific POS_Reseller Revenue From Client...    1.150841
Region_Midwest Revenue From Client Past Two Yea...    1.141131
Region_Pacific POS_Reseller Opportunity Amount ...    1.139401
Region_Pacific Competitor_None Client Size By E...    1.128128
Competitor_None Client Size By Employee Count_4...    1.121842
Region_Southwest POS_Reseller Client Size By Re...    1.117962
Region_Southwest Competitor_Unknown Opportunity...    1.114833
Region_Pacific Client Size By Revenue_5 Opportu...    1.074470
Region_Midwest Revenue From Client Past Two Yea...    1.060201
Region_Northwest Revenue From Client Past Two Y...    1.037229
Region_Northeast Client Size By Revenue_5 Clien...    1.020037
Region_Southwest Revenue From Client Past Two Y...    1.019584
Client Size By Revenue_4 Revenue From Client Pa...    1.014200
Region_Southeast Revenue From Client Past Two Y...    1.010577
Competitor_Unknown Client Size By Revenue_5 Opp...    1.006205
Region_Southwest Client Size By Employee Count_...    1.004756
Region_Pacific POS_Reseller Revenue From Client...    0.999764
Client Size By Employee Count_3 Revenue From Cl...    0.995048
POS_Other Competitor_None Opportunity Amount > ...    0.994568
Category_Performance & Non-auto Region_Southwes...    0.994424
Client Size By Revenue_5 Client Size By Employe...    0.993421
POS_Other Revenue From Client Past Two Years_2 ...    0.983238
Region_Northwest POS_Other Revenue From Client ...    0.978994
Region_Midwest Revenue From Client Past Two Yea...    0.977774
Category_Performance & Non-auto Revenue From Cl...    0.972493
POS_Reseller Competitor_Unknown Client Size By ...    0.969549
Client Size By Revenue_3 Client Size By Employe...    0.958709
Region_Northwest Revenue From Client Past Two Y...    0.956996
Competitor_None Client Size By Employee Count_4...    0.955232
Category_Performance & Non-auto Client Size By ...    0.950745
Client Size By Revenue_4 Revenue From Client Pa...    0.949202
Region_Northwest Revenue From Client Past Two Y...    0.947911
Region_Southwest Client Size By Employee Count_...    0.946043
Region_Southeast Client Size By Employee Count_...    0.944735
Region_Southwest Client Size By Revenue_3 Oppor...    0.941076
POS_Other Revenue From Client Past Two Years_4 ...    0.932716
Client Size By Revenue_2 Client Size By Employe...    0.932441
Competitor_Unknown Client Size By Employee Coun...    0.932400
Category_Performance & Non-auto Client Size By ...    0.926611
Region_Northwest POS_Reseller Opportunity Amoun...    0.921110